version: '3.8'

#local:docker
services:
    #node Service
    app:
        build:
            context: node
            dockerfile: Dockerfile
        container_name: app #nodejs
        ports: 3000:3000
        volumes:
            - ./src:/usr/src
            - /usr/src/node_modules
        networks:
            - app-network
  
    # Nginx Service
    # webserver:
    #     image: nginx:latest
    #     container_name: webserver
    #     volumes: 
    #         - ./src:/var/www
    #         - ./nginx/conf.d/:/etc/nginx/conf.d/
    #     ports:
    #         - 8080:80
    #         - 443:443
    #     networks:
    #         - app-network

    # #MySQL/MongoDB Service
    # db:
    #     image: mysql:5.7.22
    #     container_name: db
    #     env_file: ./.env
    #     volumes: 
    #         - mysql:/var/lib/mysql
    #         - ./mysql/my.cnf:/etc/mysql/my.cnf
    #     restart: unless-stopped
    #     tty: true
    #     ports:
    #         # - "8889:3306"
    #         - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    #     environment:
    #         MYSQL_DATABASE: app_db
    #         MYSQL_ROOT_PASSWORD: root
    #         MYSQL_PASSWORD: root
    #         MYSQL_USER: root
    #         SERVICE_TAGS: dev
    #         SERVICE_NAME: mysql
    #     networks:
    #         - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge

#Volumes
volumes:
    # mysql: