version: '3.8'

#local:docker
services:
    #nodejs Service
    app:
        build:
            context: .
            dockerfile: ./node/Dockerfile
        container_name: app
        volumes:
            - ./src:/usr/app/src
            - /usr/app/src/node_modules
            # - /src/node_modules:/usr/app/src/node_modules
        ports: 
            - 49160:3000
        networks:
            - app-network
            
#Docker Networks
networks:
    app-network:
        driver: bridge
